# Generated by Django 5.0.2 on 2024-03-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filerequest',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='filerequest',
            name='api_calls',
            field=models.IntegerField(default=0),
        ),
    ]
